swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:  
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/main-account:
    get: 
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: User Profile API
      description: API for getting the user's main account
      parameters: 
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces: 
        - application/json
      responses: 
        "200": 
          description: "main account successfully retrieved"
          schema: 
            $ref: '#/definitions/TransactionList'
        "403":
          description: "Unauthorized"
        "500":
          desciption: "internal server error"

  /user/profile/main-account/{main-accountID}/details:
    get: 
      security:
        - Bearer: []
      tags:
         - Transaction Module
      summary: User Profile API
      description: API for getting the main account transaction
      parameters: 
        - in: path
          name: transactionID
          schema: 
            type: integer
          required: true 
          description: Numeric ID of the transaction to get
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: query
          name : limit
          type: integer
          description: the number of items to return
        - in: query
          name: month
          format: MM:YYYY
          description: the month of transaction to get
      produces:
        - application/json
      responses: 
        "200": 
          description: Transaction detail retrieved successfully
          schema: 
            $ref: "#/definitions/TransactionDetail"
        "404":
          description: No transaction with such ID
        "403":
          description: "unauthorized"
        "500":
          description: Internal server error
    put: 
      security: 
        Bearer: []
      tags: 
        - Transaction Module
      summary: User Profile API
      description: API for updating transaction details
      parameters: 
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string 
        - in: body 
          name: body
          description: Update user profile attributes
          required: true
          schema: 
            $ref: "#/definitions/TransactionAttributes"
      produces: 
        application/json
      responses: 
        "200":
          description: "Transaction attributes have been updated successfully"
        "500": 
          description: "Internal server error"
  /user/profile/savings:
    get: 
      security:
        - Bearer: []
      tags:
         - Transaction Module
      summary: User Profile API
      description: API for getting the user's savings account
      parameters: 
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces: 
        - application/json
      responses: 
        "200": 
          description: "main account successfully retrieved"
          schema: 
            $ref: '#/definitions/TransactionList'
        "403":
          description: "unauthorized"
        "500":
          desciption: "internal server error"

  /user/profile/savings/{savingsID}/details:
    get: 
      security:
        - Bearer: []
      tags:
         - Transaction Module
      summary: User Profile API
      description: API for getting the user's saving account transaction ID
      parameters: 
        - in: path
          name: transactionID
          schema: 
            type: integer
          required: true 
          description: Numeric ID of the transaction to get
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: query
          name : limit
          type: integer
          description: the number of items to return
        - in: query
          name: month
          format: MM:YYYY
          description: the month of transaction to get

      produces:
        - application/json
      responses: 
        "200": 
          description: Transaction detail retrieved successfully
          schema: 
            $ref: "#/definitions/TransactionDetail"
        "404":
          description: No transaction with such ID
        "403":
          description: "Unauthorized"
        "500":
          description: Internal server error
    put: 
      security: 
        Bearer: []
      tags: 
         - Transaction Module
      summary: User Profile API
      description: API for updating transaction details
      parameters: 
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string 
        - in: body 
          name: body
          description: Update user profile attributes
          required: true
          schema: 
            $ref: "#/definitions/TransactionAttributes"
      produces: 
        application/json
      responses: 
        "200":
          description: "Transaction attributes have been updated successfully"
        "500": 
          description: "Internal server error"
  /user/profile/credit-card:
    get: 
      security:
        - Bearer: []
      tags:
       - Transaction Module
      summary: User Profile API
      description: API for getting the user's credit card account
      parameters: 
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces: 
        - application/json
      responses: 
        "200": 
          description: "main account successfully retrieved"
          schema: 
            $ref: '#/definitions/TransactionList'
        "403":
          description: "Unauthorized"
        "500":
          desciption: "internal server error"
  /user/profile/credit-card/{credit-cardID}/details:
    get: 
      security:
        - Bearer: []
      tags:
         - Transaction Module
      summary: User Profile API
      description: API for getting the main account transaction
      parameters: 
        - in: path
          name: transactionID
          schema: 
            type: integer
          required: true 
          description: Numeric ID of the transaction to get
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: query
          name : limit
          type: integer
          description: the number of items to return
        - in: query
          name: month
          format: MM:YYYY
          description: the month of transaction to get
      produces:
        - application/json
      responses: 
        "200": 
          description: Transaction detail retrieved successfully
          schema: 
            $ref: "#/definitions/TransactionDetail"
        "404":
          description: No transaction with such ID
        "403":
          description: "Unauthorized"
        "500":
          description: Internal server error
    put: 
      security: 
        Bearer: []
      tags: 
       - Transaction Module
      summary: User Profile API
      description: API for updating transaction details
      parameters: 
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string 
        - in: body 
          name: body
          description: Update user profile attributes
          required: true
          schema: 
            $ref: "#/definitions/TransactionAttributes"
      produces: 
        application/json
      responses: 
        "200":
          description: "Transaction attributes have been updated successfully"
        "500": 
          description: "Internal server error"
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  TransactionList: 
    type: object
    properties:
      status: 
        type: integer
      message: 
        type: string
      body: 
        type: array
        items: 
          type: object
          properties: 
            id: 
              type: integer
            date: 
              type: string
            ammount: 
              type: integer
            origin: 
              type: string
            transacationType: 
              type: string
            category: 
              type: string
            notes: 
              type: string
  TransactionAttributes:
    type: object
    properties:
      category: 
        type: string
      notes: 
        type: string
  TransactionDetail:
    type: object
    properties: 
      id: 
          type: integer
      date: 
          type: string
      ammount: 
          type: integer
      origin: 
          type: string
      transacationType: 
          type: string
      category: 
          type: string
      notes: 
          type: string